apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server/metrics-server:v0.5.0
        command:
          - /metrics-server
          - --kubelet-insecure-tls
          - --cert-dir=/tmp/certs
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "250m"
        volumeMounts:
        - name: certs
          mountPath: /tmp/certs
      volumes:
        - name: certs
          emptyDir: {}
